---
apiVersion: database.azure.crossplane.io/v1beta1
kind: SQLServerClass
metadata:
  name: sqlservermysql-standard
  labels:
    example: "true"
specTemplate:
  forProvider:
    administratorLogin: myadmin
    resourceGroupNameRef:
      name: mysql-example
    location: West US 2
    sslEnforcement: Disabled
    version: "5.7"
    sku:
      # Note that Basic servers do not support virtual network rules
      tier: GeneralPurpose
      capacity: 2
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretsToNamespace: crossplane-system
  providerRef:
    name: example
  reclaimPolicy: Delete
