apiVersion: network.azure.crossplane.io/v1alpha3
kind: PublicIPAddress
metadata:
  name: example-public-ip-address
spec:
  forProvider:
    resourceGroupNameRef:
      name: example-rg
    allocationMethod: Static
    version: IPv4
    sku:
      name: Standard
    location: West US 2
    dnsSettings:
      domainNameLabel: crossplane-example
    tags:
      application: crossplane
  providerConfigRef:
    name: example
