id: aksclusterclass
title: AKS Cluster Class
titlePlural: AKS Cluster Classes
category: Compute
overviewShort: "An AKSClusterClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
overview: |
 An AKSClusterClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource.
readme: |
 Cloud-specific resource classes are used to define a reusable configuration for a specific managed service. This class provides a managed Kubernetes cluster, which is satisfied by [Azure Kubernetes Service](https://docs.microsoft.com/en-us/azure/aks/).

 Full documentation can be found in the Crossplane [API Reference docs](https://crossplane.io/docs/master/api/crossplaneio/stack-azure/compute-azure-crossplane-io-v1alpha2.html#AKSClusterClass).
