id: redisclass
title: Azure Cache for Redis Class
titlePlural: Azure Cache for Redis Classes
category: Cache
overviewShort: "A RedisClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource."
overview: |
 A RedisClass is a non-portable resource class. It defines the desired spec of resource claims that use it to dynamically provision a managed resource.
readme: |
 Cloud-specific resource classes are used to define a reusable configuration for a specific managed service. This class provides Redis caches, which are satisfied by [Azure Cache for Redis](https://azure.microsoft.com/en-us/services/cache/).

 Full documentation can be found in the Crossplane [API Reference docs](https://crossplane.io/docs/0.8/api/crossplaneio/stack-azure/compute-azure-crossplane-io-v1alpha3.html#SQLServerClass).
