---
apiVersion: compute.azure.crossplane.io/v1alpha3
kind: AKSClusterClass
metadata:
  name: akscluster-standard
  labels:
    example: "true"
specTemplate:
  writeConnectionSecretsToNamespace: crossplane-system
  resourceGroupName: group-westus-1
  location: West US 2
  version: "1.12.8"
  nodeCount: 1
  nodeVMSize: Standard_B2s
  dnsNamePrefix: crossplane-aks
  disableRBAC: false
  # It is a bug that this field is required by Azure cluster classes; it is not
  # used. Service principal secrets for dynamically provisioned claims are
  # written to writeConnectionSecretsToNamespace.
  writeServicePrincipalTo:
    name: unused
    namespace: unused
  providerRef:
    name: example
  reclaimPolicy: Delete
