---
apiVersion: database.azure.crossplane.io/v1beta1
kind: SQLServerClass
metadata:
  name: sqlserverpostgresql-standard
  labels:
    example: "true"
specTemplate:
  forProvider:
    administratorLogin: myadmin
    resourceGroupName: group-westus-1
    location: West US
    sslEnforcement: Disabled
    version: "9.6"
    sku:
      tier: Basic
      capacity: 1
      family: Gen5
    storageProfile:
      storageMB: 20480
  writeConnectionSecretsToNamespace: crossplane-system
  providerRef:
    name: example
  reclaimPolicy: Delete
