---
apiVersion: database.crossplane.io/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: postgres-example
  annotations:
    crossplane.io/external-name: postgres-example
spec:
  classSelector:
    matchLabels:
      example: "true"
  writeConnectionSecretToRef:
    name: postgresqlconn
  engineVersion: "9.6"
---
# This is not a claim, but it is required to actually access the dynamically
# provisioned managed resource.
apiVersion: database.azure.crossplane.io/v1alpha3
kind: PostgreSQLServerVirtualNetworkRule
metadata:
  name: postgres-example
spec:
  # Note that this serverName relies on the external-name annotation of the
  # claim above being set.
  serverName: postgres-example
  resourceGroupNameRef:
    name: postgres-example
  properties:
    virtualNetworkSubnetIdRef:
      name: postgres-example
  reclaimPolicy: Delete
  providerRef:
    name: example
---
# This is not a claim, but it is required to actually access the dynamically
# provisioned managed resource.
apiVersion: database.azure.crossplane.io/v1alpha3
kind: PostgreSQLServerFirewallRule
metadata:
  name: postgresql-example
spec:
  forProvider:
    # Note that this serverName relies on the external-name annotation of the
    # claim above being set.
    serverName: postgresql-example
    resourceGroupNameRef:
      name: postgresql-example
    properties:
      startIpAddress: 127.0.0.1
      endIpAddress: 127.0.0.2
  reclaimPolicy: Delete
  providerRef:
    name: example

